package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunInErrorViewRowClient extends RowImpl
{
  /**This is the default constructor (do not remove)
   */
  public BatchRunInErrorViewRowClient()
  {
  }

  public Integer getBrunid()
  {
    return (Integer)getAttribute("Brunid");
  }

  public String getBrunpath()
  {
    return (String)getAttribute("Brunpath");
  }

  public Integer getTauid()
  {
    return (Integer)getAttribute("Tauid");
  }

  public Integer getTrunid()
  {
    return (Integer)getAttribute("Trunid");
  }

  public String getTrunpath()
  {
    return (String)getAttribute("Trunpath");
  }

  public void setBrunid(Integer value)
  {
    setAttribute("Brunid", value);
  }

  public void setBrunpath(String value)
  {
    setAttribute("Brunpath", value);
  }

  public void setTauid(Integer value)
  {
    setAttribute("Tauid", value);
  }

  public void setTrunid(Integer value)
  {
    setAttribute("Trunid", value);
  }

  public void setTrunpath(String value)
  {
    setAttribute("Trunpath", value);
  }
}
