package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.batch.business.query.common.BatchRunView;
import com.cylande.unitedretail.batch.business.query.common.BatchRunViewRow;
import com.cylande.unitedretail.message.batch.BatchCriteriaType;
import com.cylande.unitedretail.message.batch.BatchRunCriteriaListType;
import com.cylande.unitedretail.message.batch.BatchRunCriteriaType;
import com.cylande.unitedretail.message.batch.BatchRunKeyType;
import com.cylande.unitedretail.message.common.criteria.CriteriaStringType;
import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunViewClient extends ViewUsageImpl implements BatchRunView
{
  /**This is the default constructor (do not remove)
   */
  public BatchRunViewClient()
  {
  }

  public boolean atLeastInstanceIsRunning(CriteriaStringType pCriteria)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "atLeastInstanceIsRunning", new String[] { "com.cylande.unitedretail.message.common.criteria.CriteriaStringType" }, new Object[] { pCriteria });
    return ((Boolean)_ret).booleanValue();
  }

  public void findLastActivationOfBatch(CriteriaStringType pCriteria)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findLastActivationOfBatch", new String[] { "com.cylande.unitedretail.message.common.criteria.CriteriaStringType" }, new Object[] { pCriteria });
    return;
  }

  public BatchRunViewRow getRowByBatchId(String pPath, Integer pId)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getRowByBatchId", new String[] { "java.lang.String", "java.lang.Integer" }, new Object[] { pPath, pId });
    return (BatchRunViewRow)_ret;
  }

  public boolean atLeastInstanceIsRunning(BatchCriteriaType pCriteria)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "atLeastInstanceIsRunning", new String[] { "com.cylande.unitedretail.message.batch.BatchCriteriaType" }, new Object[] { pCriteria });
    return ((Boolean)_ret).booleanValue();
  }


    public void findLastActivationOfBatch(BatchRunCriteriaType pCriteria)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findLastActivationOfBatch", new String[] { "com.cylande.unitedretail.message.batch.BatchRunCriteriaType" }, new Object[] { pCriteria });
    return;
  }

  public void findByCriterias(BatchRunCriteriaListType pCriterias)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"findByCriterias",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaListType"},new Object[] {pCriterias});
    return;
  }

  public BatchRunViewRow getRow(BatchRunKeyType pKey)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getRow",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType"},new Object[] {pKey});
    return (BatchRunViewRow)_ret;
  }

  public BatchRunViewRow getRowByBatchId(String pPath, Integer pId, SiteKeyType pSite)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getRowByBatchId",new String [] {"java.lang.String","java.lang.Integer","com.cylande.unitedretail.message.network.businessunit.SiteKeyType"},new Object[] {pPath, pId, pSite});
    return (BatchRunViewRow)_ret;
  }

  public void findLastActivationOfBatch(BatchCriteriaType pCriteria)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"findLastActivationOfBatch",new String [] {"com.cylande.unitedretail.message.batch.BatchCriteriaType"},new Object[] {pCriteria});
    return;
  }

  public boolean atLeastInstanceIsRunning(BatchRunCriteriaType pCriteria)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"atLeastInstanceIsRunning",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaType"},new Object[] {pCriteria});
    return ((Boolean)_ret).booleanValue();
  }
}
