package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.batch.business.query.common.BatchErrorsView;
import com.cylande.unitedretail.message.batch.BatchRunKeyType;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchErrorsViewClient extends ViewUsageImpl implements BatchErrorsView
{
  /**This is the default constructor (do not remove)
   */
  public BatchErrorsViewClient()
  {
  }

  public boolean atLeastTaskError(BatchRunKeyType pKey)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "atLeastTaskError", new String[] { "com.cylande.unitedretail.message.batch.BatchRunKeyType" }, new Object[] { pKey });
    return ((Boolean)_ret).booleanValue();
  }

  public void findTaskAuditOfBatch(BatchRunKeyType pKey)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findTaskAuditOfBatch", new String[] { "com.cylande.unitedretail.message.batch.BatchRunKeyType" }, new Object[] { pKey });
    return;
  }
}
