package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.batch.business.query.common.BatchRunInErrorView;
import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunInErrorViewClient extends ViewUsageImpl implements BatchRunInErrorView
{
  /**This is the default constructor (do not remove)
   */
  public BatchRunInErrorViewClient()
  {
  }

  public void findBatchInError()
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findBatchInError", null, null);
    return;
  }

  public void findTaskAudit(int pBatchId, SiteKeyType pSite)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findTaskAudit", new String[] { "int", "com.cylande.unitedretail.message.network.businessunit.SiteKeyType" }, new Object[] { new Integer(pBatchId), pSite });
    return;
  }
}
