package com.cylande.unitedretail.batch.business.query.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchInProgressViewRowClient extends RowImpl
{
  /**This is the default constructor (do not remove)
   */
  public BatchInProgressViewRowClient()
  {
  }

  public String getBatchCode()
  {
    return (String)getAttribute("BatchCode");
  }

  public String getBatchMode()
  {
    return (String)getAttribute("BatchMode");
  }

  public String getBatchType()
  {
    return (String)getAttribute("BatchType");
  }

  public Date getCreationTime()
  {
    return (Date)getAttribute("CreationTime");
  }

  public String getCreationUserCode()
  {
    return (String)getAttribute("CreationUserCode");
  }

  public String getDomain()
  {
    return (String)getAttribute("Domain");
  }

  public Date getEndTime()
  {
    return (Date)getAttribute("EndTime");
  }

  public Number getId()
  {
    return (Number)getAttribute("Id");
  }

  public Number getInError()
  {
    return (Number)getAttribute("InError");
  }

  public Date getModificationTime()
  {
    return (Date)getAttribute("ModificationTime");
  }

  public String getModificationUserCode()
  {
    return (String)getAttribute("ModificationUserCode");
  }

  public Number getParentId()
  {
    return (Number)getAttribute("ParentId");
  }

  public String getSiteCode()
  {
    return (String)getAttribute("SiteCode");
  }

  public Date getStartTime()
  {
    return (Date)getAttribute("StartTime");
  }

  public Number getState()
  {
    return (Number)getAttribute("State");
  }

  public void setBatchCode(String value)
  {
    setAttribute("BatchCode", value);
  }

  public void setBatchMode(String value)
  {
    setAttribute("BatchMode", value);
  }

  public void setBatchType(String value)
  {
    setAttribute("BatchType", value);
  }

  public void setCreationTime(Date value)
  {
    setAttribute("CreationTime", value);
  }

  public void setCreationUserCode(String value)
  {
    setAttribute("CreationUserCode", value);
  }

  public void setDomain(String value)
  {
    setAttribute("Domain", value);
  }

  public void setEndTime(Date value)
  {
    setAttribute("EndTime", value);
  }

  public void setId(Number value)
  {
    setAttribute("Id", value);
  }

  public void setInError(Number value)
  {
    setAttribute("InError", value);
  }

  public void setModificationTime(Date value)
  {
    setAttribute("ModificationTime", value);
  }

  public void setModificationUserCode(String value)
  {
    setAttribute("ModificationUserCode", value);
  }

  public void setParentId(Number value)
  {
    setAttribute("ParentId", value);
  }

  public void setSiteCode(String value)
  {
    setAttribute("SiteCode", value);
  }

  public void setStartTime(Date value)
  {
    setAttribute("StartTime", value);
  }

  public void setState(Number value)
  {
    setAttribute("State", value);
  }
}
