package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.batch.business.query.common.BatchInProgressView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchInProgressViewClient extends ViewUsageImpl implements BatchInProgressView
{
  /**This is the default constructor (do not remove)
   */
  public BatchInProgressViewClient()
  {
  }

  public void findLastBatchByPath(String pPath)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"findLastBatchByPath",new String [] {"java.lang.String"},new Object[] {pPath});
    return;
  }
}
