package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileProviderTraceViewRowClient extends RowImpl
{
  /**This is the default constructor (do not remove)
   */
  public FileProviderTraceViewRowClient()
  {
  }

  public String getDomain()
  {
    return (String)getAttribute("Domain");
  }

  public String getFileName()
  {
    return (String)getAttribute("FileName");
  }

  public String getFilePath()
  {
    return (String)getAttribute("FilePath");
  }

  public Integer getID()
  {
    return (Integer)getAttribute("ID");
  }

  public Booleans getInError()
  {
    return (Booleans)getAttribute("InError");
  }

  public String getProviderName()
  {
    return (String)getAttribute("ProviderName");
  }

  public String getSiteCode()
  {
    return (String)getAttribute("SiteCode");
  }

  public String getTaskCode()
  {
    return (String)getAttribute("TaskCode");
  }

  public Integer getTaskId()
  {
    return (Integer)getAttribute("TaskId");
  }

  public void setDomain(String value)
  {
    setAttribute("Domain", value);
  }

  public void setFileName(String value)
  {
    setAttribute("FileName", value);
  }

  public void setFilePath(String value)
  {
    setAttribute("FilePath", value);
  }

  public void setID(Integer value)
  {
    setAttribute("ID", value);
  }

  public void setInError(Booleans value)
  {
    setAttribute("InError", value);
  }

  public void setProviderName(String value)
  {
    setAttribute("ProviderName", value);
  }

  public void setSiteCode(String value)
  {
    setAttribute("SiteCode", value);
  }

  public void setTaskCode(String value)
  {
    setAttribute("TaskCode", value);
  }

  public void setTaskId(Integer value)
  {
    setAttribute("TaskId", value);
  }
}
