package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.batch.business.query.common.FileProviderTraceView;
import com.cylande.unitedretail.batch.business.query.common.FileProviderTraceViewRow;
import com.cylande.unitedretail.message.batch.FileProviderTraceCriteriaListType;
import com.cylande.unitedretail.message.batch.FileProviderTraceKeyType;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileProviderTraceViewClient extends ViewUsageImpl implements FileProviderTraceView
{
  /**This is the default constructor (do not remove)
   */
  public FileProviderTraceViewClient()
  {
  }

  public void findByCriterias(FileProviderTraceCriteriaListType pCriterias)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"findByCriterias",new String [] {"com.cylande.unitedretail.message.batch.FileProviderTraceCriteriaListType"},new Object[] {pCriterias});
    return;
  }

  public FileProviderTraceViewRow getRow(FileProviderTraceKeyType pKey)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getRow",new String [] {"com.cylande.unitedretail.message.batch.FileProviderTraceKeyType"},new Object[] {pKey});
    return (FileProviderTraceViewRow)_ret;
  }
}
