package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Timestamp;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProviderCrcViewRowClient extends RowImpl
{
  /**This is the default constructor (do not remove)
   */
  public ProviderCrcViewRowClient()
  {
  }

  public String getBatchName()
  {
    return (String)getAttribute("BatchName");
  }

  public String getCrc()
  {
    return (String)getAttribute("Crc");
  }

  public Timestamp getCreationTime()
  {
    return (Timestamp)getAttribute("CreationTime");
  }

  public String getCreationUserCode()
  {
    return (String)getAttribute("CreationUserCode");
  }

  public Timestamp getModificationTime()
  {
    return (Timestamp)getAttribute("ModificationTime");
  }

  public String getModificationUserCode()
  {
    return (String)getAttribute("ModificationUserCode");
  }

  public Booleans getOverridden()
  {
    return (Booleans)getAttribute("Overridden");
  }

  public void setBatchName(String value)
  {
    setAttribute("BatchName", value);
  }

  public void setCrc(String value)
  {
    setAttribute("Crc", value);
  }

  public void setModificationTime(Timestamp value)
  {
    setAttribute("ModificationTime", value);
  }

  public void setOverridden(Booleans value)
  {
    setAttribute("Overridden", value);
  }
}
