package com.cylande.unitedretail.batch.business.query.client;

import com.cylande.unitedretail.batch.business.query.common.TaskRunView;
import com.cylande.unitedretail.batch.business.query.common.TaskRunViewRow;
import com.cylande.unitedretail.message.batch.TaskRunCriteriaListType;
import com.cylande.unitedretail.message.batch.TaskRunKeyType;
import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskRunViewClient extends ViewUsageImpl implements TaskRunView
{
  /**This is the default constructor (do not remove)
   */
  public TaskRunViewClient()
  {
  }

  public void findByCriterias(TaskRunCriteriaListType pCriterias)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"findByCriterias",new String [] {"com.cylande.unitedretail.message.batch.TaskRunCriteriaListType"},new Object[] {pCriterias});
    return;
  }

  public TaskRunViewRow getRow(TaskRunKeyType pKey)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getRow",new String [] {"com.cylande.unitedretail.message.batch.TaskRunKeyType"},new Object[] {pKey});
    return (TaskRunViewRow)_ret;
  }

  public TaskRunViewRow getRowByTaskId(String pPath, Integer pId, SiteKeyType pSite)
  {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getRowByTaskId",new String [] {"java.lang.String","java.lang.Integer","com.cylande.unitedretail.message.network.businessunit.SiteKeyType"},new Object[] {pPath, pId, pSite});
    return (TaskRunViewRow)_ret;
  }
}
