package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.query.common.BatchRunNameListViewRow;
import com.cylande.unitedretail.framework.business.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunNameListViewRowImpl extends ViewRowImpl implements BatchRunNameListViewRow
{
  public static final int BRUNPATH = 0;

  /**This is the default constructor (do not remove)
   */
  public BatchRunNameListViewRowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute Brunpath
   */
  public String getBrunpath()
  {
    return (String)getAttributeInternal(BRUNPATH);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Brunpath
   */
  public void setBrunpath(String value)
  {
    setAttributeInternal(BRUNPATH, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case BRUNPATH:
        return getBrunpath();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }
}
