package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.query.common.BatchRunInErrorView;
import com.cylande.unitedretail.framework.business.jbo.server.ViewObjectImpl;
import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunInErrorViewImpl extends ViewObjectImpl implements BatchRunInErrorView
{
  /**This is the default constructor (do not remove)
   */
  public BatchRunInErrorViewImpl()
  {
  }

  /**This is the default constructor (do not remove)
   */
  public void findBatchInError()
  {
    clearViewCriterias();
    setQuery(getQuery() + " WHERE TRUNVIEW.TRUNID = TAUD.TASK" + " AND TRUNVIEW.TRUNSITE = TAUD.SITE_CODE");
    executeQuery();
  }

  public void findTaskAudit(int pBatchId, SiteKeyType pSite)
  {
    clearViewCriterias();
    if (pSite != null && pSite.getCode() != null)
    {
      setQuery(getQuery() + " WHERE TRUNVIEW.TRUNID = TAUD.TASK AND BRUNID = " + pBatchId + " AND   TRUNVIEW.TRUNSITE = TAUD.SITE_CODE" + " AND   TAUD.SITE_CODE = '" + pSite.getCode() + "'");
    }
    else
    {
      setQuery(getQuery() + " WHERE TRUNVIEW.TRUNID = TAUD.TASK AND BRUNID = " + pBatchId + " AND TRUNVIEW.TRUNSITE = TAUD.SITE_CODE");
    }
    executeQuery();
  }
}
