package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.query.common.BatchInProgressView;

import com.cylande.unitedretail.framework.business.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchInProgressViewImpl extends ViewObjectImpl implements BatchInProgressView
{
  /**This is the default constructor (do not remove)
   */
  public BatchInProgressViewImpl()
  {
    //Empty construtory
  }

  public void findLastBatchByPath(String pPath)
  {
    setWhereClause("BATCH_CODE  = '" + pPath + "'");
    executeQuery();
  }
}
