package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.entity.BatchRunImpl;
import com.cylande.unitedretail.batch.business.entity.TaskAuditImpl;
import com.cylande.unitedretail.batch.business.entity.TaskRunImpl;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Timestamp;
import com.cylande.unitedretail.framework.business.jbo.server.ViewRowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchErrorsViewRowImpl extends ViewRowImpl
{
  public static final int CREATIONTIME = 0;
  public static final int CREATIONTIME1 = 10;
  public static final int CREATIONUSERCODE1 = 11;
  public static final int MODIFICATIONTIME1 = 12;
  public static final int MODIFICATIONUSERCODE1 = 13;
  public static final int ID1 = 15;
  public static final int EVENTTIME1 = 16;
  public static final int ERRORCODE1 = 17;
  public static final int ERRORMESSAGE1 = 18;
  public static final int TASK1 = 19;
  public static final int CREATIONUSERCODE = 1;
  public static final int MODIFICATIONTIME = 2;
  public static final int MODIFICATIONUSERCODE = 3;
  public static final int TASKCODE = 4;
  public static final int ID = 5;
  public static final int SITECODE = 6;
  public static final int EVENTTIME = 7;
  public static final int ERRORCODE = 8;
  public static final int ERRORMESSAGE = 9;
  public static final int TASK = 10;
  public static final int CREATIONTIME1_1 = 11;
  public static final int CREATIONUSERCODE1_1 = 12;
  public static final int MODIFICATIONTIME1_1 = 13;
  public static final int MODIFICATIONUSERCODE1_1 = 14;
  public static final int PATH = 15;
  public static final int ID1_1 = 16;
  public static final int EVENTTIME1_1 = 17;
  public static final int ERRORCODE1_1 = 18;
  public static final int ERRORMESSAGE1_1 = 19;
  public static final int TASK1_1 = 20;
  public static final int SITECODE1 = 21;

  /**This is the default constructor (do not remove)
   */
  public BatchErrorsViewRowImpl()
  {
  }

  /**Gets BatchRun entity object.
   */
  public BatchRunImpl getBatchRun()
  {
    return (BatchRunImpl)getEntity(0);
  }

  /**Gets TaskRun entity object.
   */
  public TaskRunImpl getTaskRun()
  {
    return (TaskRunImpl)getEntity(1);
  }

  /**Gets TaskAudit entity object.
   */
  public TaskAuditImpl getTaskAudit()
  {
    return (TaskAuditImpl)getEntity(2);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case CREATIONTIME:
        return getCreationTime();
      case CREATIONUSERCODE:
        return getCreationUserCode();
      case MODIFICATIONTIME:
        return getModificationTime();
      case MODIFICATIONUSERCODE:
        return getModificationUserCode();
      case TASKCODE:
        return getTaskCode();
      case ID:
        return getId();
      case SITECODE:
        return getSiteCode();
      case EVENTTIME:
        return getEventTime();
      case ERRORCODE:
        return getErrorCode();
      case ERRORMESSAGE:
        return getErrorMessage();
      case TASK:
        return getTask();
      case CREATIONTIME1_1:
        return getCreationTime1_1();
      case CREATIONUSERCODE1_1:
        return getCreationUserCode1_1();
      case MODIFICATIONTIME1_1:
        return getModificationTime1_1();
      case MODIFICATIONUSERCODE1_1:
        return getModificationUserCode1_1();
      case PATH:
        return getPath();
      case ID1_1:
        return getId1_1();
      case EVENTTIME1_1:
        return getEventTime1_1();
      case ERRORCODE1_1:
        return getErrorCode1_1();
      case ERRORMESSAGE1_1:
        return getErrorMessage1_1();
      case TASK1_1:
        return getTask1_1();
      case SITECODE1:
        return getSiteCode1();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case CREATIONTIME:
        setCreationTime((Date)value);
        return;
      case CREATIONUSERCODE:
        setCreationUserCode((String)value);
        return;
      case MODIFICATIONTIME:
        setModificationTime((Date)value);
        return;
      case MODIFICATIONUSERCODE:
        setModificationUserCode((String)value);
        return;
      case TASKCODE:
        setTaskCode((String)value);
        return;
      case ID:
        setId((Number)value);
        return;
      case SITECODE:
        setSiteCode((String)value);
        return;
      case EVENTTIME:
        setEventTime((Date)value);
        return;
      case ERRORCODE:
        setErrorCode((String)value);
        return;
      case ERRORMESSAGE:
        setErrorMessage((String)value);
        return;
      case TASK:
        setTask((Number)value);
        return;
      case CREATIONTIME1_1:
        setCreationTime1_1((Timestamp)value);
        return;
      case CREATIONUSERCODE1_1:
        setCreationUserCode1_1((String)value);
        return;
      case MODIFICATIONTIME1_1:
        setModificationTime1_1((Timestamp)value);
        return;
      case MODIFICATIONUSERCODE1_1:
        setModificationUserCode1_1((String)value);
        return;
      case PATH:
        setPath((String)value);
        return;
      case ID1_1:
        setId1_1((Integer)value);
        return;
      case EVENTTIME1_1:
        setEventTime1_1((Timestamp)value);
        return;
      case ERRORCODE1_1:
        setErrorCode1_1((String)value);
        return;
      case ERRORMESSAGE1_1:
        setErrorMessage1_1((String)value);
        return;
      case TASK1_1:
        setTask1_1((Integer)value);
        return;
      case SITECODE1:
        setSiteCode1((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }

  /**Gets the attribute value for TASK_CODE using the alias name Path
   */
  public String getPath()
  {
    return (String)getAttributeInternal(PATH);
  }

  /**Sets <code>value</code> as attribute value for TASK_CODE using the alias name Path
   */
  public void setPath(String value)
  {
    setAttributeInternal(PATH, value);
  }

  /**Gets the attribute value for ID using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**Sets <code>value</code> as attribute value for ID using the alias name Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**Gets the attribute value for TASK using the alias name Task
   */
  public Number getTask()
  {
    return (Number)getAttributeInternal(TASK);
  }

  /**Sets <code>value</code> as attribute value for TASK using the alias name Task
   */
  public void setTask(Number value)
  {
    setAttributeInternal(TASK, value);
  }

  /**Gets the attribute value for CREATION_TIME using the alias name CreationTime
   */
  public Date getCreationTime()
  {
    return (Date)getAttributeInternal(CREATIONTIME);
  }

  /**Gets the attribute value for CREATION_USER_CODE using the alias name CreationUserCode
   */
  public String getCreationUserCode()
  {
    return (String)getAttributeInternal(CREATIONUSERCODE);
  }

  /**Gets the attribute value for MODIFICATION_TIME using the alias name ModificationTime
   */
  public Date getModificationTime()
  {
    return (Date)getAttributeInternal(MODIFICATIONTIME);
  }

  /**Gets the attribute value for MODIFICATION_USER_CODE using the alias name ModificationUserCode
   */
  public String getModificationUserCode()
  {
    return (String)getAttributeInternal(MODIFICATIONUSERCODE);
  }

  /**Gets the attribute value for EVENT_TIME using the alias name EventTime
   */
  public Date getEventTime()
  {
    return (Date)getAttributeInternal(EVENTTIME);
  }

  /**Sets <code>value</code> as attribute value for EVENT_TIME using the alias name EventTime
   */
  public void setEventTime(Date value)
  {
    setAttributeInternal(EVENTTIME, value);
  }

  /**Gets the attribute value for ERROR_CODE using the alias name ErrorCode
   */
  public String getErrorCode()
  {
    return (String)getAttributeInternal(ERRORCODE);
  }

  /**Sets <code>value</code> as attribute value for ERROR_CODE using the alias name ErrorCode
   */
  public void setErrorCode(String value)
  {
    setAttributeInternal(ERRORCODE, value);
  }

  /**Gets the attribute value for ERROR_MESSAGE using the alias name ErrorMessage
   */
  public String getErrorMessage()
  {
    return (String)getAttributeInternal(ERRORMESSAGE);
  }

  /**Sets <code>value</code> as attribute value for ERROR_MESSAGE using the alias name ErrorMessage
   */
  public void setErrorMessage(String value)
  {
    setAttributeInternal(ERRORMESSAGE, value);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationTime
   */
  public void setCreationTime(Date value)
  {
    setAttributeInternal(CREATIONTIME, value);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationUserCode
   */
  public void setCreationUserCode(String value)
  {
    setAttributeInternal(CREATIONUSERCODE, value);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ModificationTime
   */
  public void setModificationTime(Date value)
  {
    setAttributeInternal(MODIFICATIONTIME, value);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ModificationUserCode
   */
  public void setModificationUserCode(String value)
  {
    setAttributeInternal(MODIFICATIONUSERCODE, value);
  }

  /**Gets the attribute value for the calculated attribute TaskCode
   */
  public String getTaskCode()
  {
    return (String)getAttributeInternal(TASKCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TaskCode
   */
  public void setTaskCode(String value)
  {
    setAttributeInternal(TASKCODE, value);
  }

  /**Gets the attribute value for the calculated attribute CreationTime1
   */
  public Timestamp getCreationTime1()
  {
    return (Timestamp)getAttributeInternal(CREATIONTIME1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationTime1
   */
  public void setCreationTime1(Timestamp value)
  {
    setAttributeInternal(CREATIONTIME1, value);
  }

  /**Gets the attribute value for the calculated attribute CreationUserCode1
   */
  public String getCreationUserCode1()
  {
    return (String)getAttributeInternal(CREATIONUSERCODE1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationUserCode1
   */
  public void setCreationUserCode1(String value)
  {
    setAttributeInternal(CREATIONUSERCODE1, value);
  }

  /**Gets the attribute value for the calculated attribute ModificationTime1
   */
  public Timestamp getModificationTime1()
  {
    return (Timestamp)getAttributeInternal(MODIFICATIONTIME1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ModificationTime1
   */
  public void setModificationTime1(Timestamp value)
  {
    setAttributeInternal(MODIFICATIONTIME1, value);
  }

  /**Gets the attribute value for the calculated attribute ModificationUserCode1
   */
  public String getModificationUserCode1()
  {
    return (String)getAttributeInternal(MODIFICATIONUSERCODE1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ModificationUserCode1
   */
  public void setModificationUserCode1(String value)
  {
    setAttributeInternal(MODIFICATIONUSERCODE1, value);
  }

  /**Gets the attribute value for the calculated attribute Id1
   */
  public Integer getId1()
  {
    return (Integer)getAttributeInternal(ID1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Id1
   */
  public void setId1(Integer value)
  {
    setAttributeInternal(ID1, value);
  }

  /**Gets the attribute value for the calculated attribute EventTime1
   */
  public Timestamp getEventTime1()
  {
    return (Timestamp)getAttributeInternal(EVENTTIME1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EventTime1
   */
  public void setEventTime1(Timestamp value)
  {
    setAttributeInternal(EVENTTIME1, value);
  }

  /**Gets the attribute value for the calculated attribute ErrorCode1
   */
  public String getErrorCode1()
  {
    return (String)getAttributeInternal(ERRORCODE1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ErrorCode1
   */
  public void setErrorCode1(String value)
  {
    setAttributeInternal(ERRORCODE1, value);
  }

  /**Gets the attribute value for the calculated attribute ErrorMessage1
   */
  public String getErrorMessage1()
  {
    return (String)getAttributeInternal(ERRORMESSAGE1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ErrorMessage1
   */
  public void setErrorMessage1(String value)
  {
    setAttributeInternal(ERRORMESSAGE1, value);
  }

  /**Gets the attribute value for the calculated attribute Task1
   */
  public Integer getTask1()
  {
    return (Integer)getAttributeInternal(TASK1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Task1
   */
  public void setTask1(Integer value)
  {
    setAttributeInternal(TASK1, value);
  }

  /**Gets the attribute value for the calculated attribute SiteCode
   */
  public String getSiteCode()
  {
    return (String)getAttributeInternal(SITECODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute SiteCode
   */
  public void setSiteCode(String value)
  {
    setAttributeInternal(SITECODE, value);
  }

  /**Gets the attribute value for the calculated attribute CreationTime1_1
   */
  public Timestamp getCreationTime1_1()
  {
    return (Timestamp)getAttributeInternal(CREATIONTIME1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationTime1_1
   */
  public void setCreationTime1_1(Timestamp value)
  {
    setAttributeInternal(CREATIONTIME1_1, value);
  }

  /**Gets the attribute value for the calculated attribute CreationUserCode1_1
   */
  public String getCreationUserCode1_1()
  {
    return (String)getAttributeInternal(CREATIONUSERCODE1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationUserCode1_1
   */
  public void setCreationUserCode1_1(String value)
  {
    setAttributeInternal(CREATIONUSERCODE1_1, value);
  }

  /**Gets the attribute value for the calculated attribute ModificationTime1_1
   */
  public Timestamp getModificationTime1_1()
  {
    return (Timestamp)getAttributeInternal(MODIFICATIONTIME1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ModificationTime1_1
   */
  public void setModificationTime1_1(Timestamp value)
  {
    setAttributeInternal(MODIFICATIONTIME1_1, value);
  }

  /**Gets the attribute value for the calculated attribute ModificationUserCode1_1
   */
  public String getModificationUserCode1_1()
  {
    return (String)getAttributeInternal(MODIFICATIONUSERCODE1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ModificationUserCode1_1
   */
  public void setModificationUserCode1_1(String value)
  {
    setAttributeInternal(MODIFICATIONUSERCODE1_1, value);
  }

  /**Gets the attribute value for the calculated attribute Id1_1
   */
  public Integer getId1_1()
  {
    return (Integer)getAttributeInternal(ID1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Id1_1
   */
  public void setId1_1(Integer value)
  {
    setAttributeInternal(ID1_1, value);
  }

  /**Gets the attribute value for the calculated attribute EventTime1_1
   */
  public Timestamp getEventTime1_1()
  {
    return (Timestamp)getAttributeInternal(EVENTTIME1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EventTime1_1
   */
  public void setEventTime1_1(Timestamp value)
  {
    setAttributeInternal(EVENTTIME1_1, value);
  }

  /**Gets the attribute value for the calculated attribute ErrorCode1_1
   */
  public String getErrorCode1_1()
  {
    return (String)getAttributeInternal(ERRORCODE1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ErrorCode1_1
   */
  public void setErrorCode1_1(String value)
  {
    setAttributeInternal(ERRORCODE1_1, value);
  }

  /**Gets the attribute value for the calculated attribute ErrorMessage1_1
   */
  public String getErrorMessage1_1()
  {
    return (String)getAttributeInternal(ERRORMESSAGE1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ErrorMessage1_1
   */
  public void setErrorMessage1_1(String value)
  {
    setAttributeInternal(ERRORMESSAGE1_1, value);
  }

  /**Gets the attribute value for the calculated attribute Task1_1
   */
  public Integer getTask1_1()
  {
    return (Integer)getAttributeInternal(TASK1_1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Task1_1
   */
  public void setTask1_1(Integer value)
  {
    setAttributeInternal(TASK1_1, value);
  }

  /**Gets the attribute value for the calculated attribute SiteCode1
   */
  public String getSiteCode1()
  {
    return (String)getAttributeInternal(SITECODE1);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute SiteCode1
   */
  public void setSiteCode1(String value)
  {
    setAttributeInternal(SITECODE1, value);
  }
}
