package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.query.common.BatchRunNameListView;
import com.cylande.unitedretail.framework.business.jbo.server.ViewObjectImpl;
import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunNameListViewImpl extends ViewObjectImpl implements BatchRunNameListView
{
  /**This is the default constructor (do not remove)
   */
  public BatchRunNameListViewImpl()
  {
  }

  /**
   * Recherche du BatchRoot
   * @param pSite
   */
  public void findBatchRunRoot(SiteKeyType pSite)
  {
    clearViewCriterias();
    if (pSite != null && pSite.getCode() != null)
    {
      setQuery(getQuery() + " AND BRUN.SITE_CODE = '" + pSite.getCode() + "' ORDER BY BRUNPATH ASC");
    }
    else
    {
      setQuery(getQuery() + " ORDER BY BRUNPATH ASC");
    }
    executeQuery();
  }

  /**
   * Recherche du BatchRoot
   * @param pSubstring
   * @param pSite
   */
  public void findBatchRunRoot(String pSubstring, SiteKeyType pSite)
  {
    clearViewCriterias();
    if (pSite != null && pSite.getCode() != null)
    {
      setQuery(getQuery() + " AND BRUN.SITE_CODE = \"" + pSite.getCode() + "\" AND BRUN.BATCH_CODE LIKE '%" + pSubstring + "%' ORDER BY BRUNPATH ASC");
    }
    else
    {
      setQuery(getQuery() + " AND BRUN.BATCH_CODE LIKE '%" + pSubstring + "%' ORDER BY BRUNPATH ASC");
    }
    executeQuery();
  }
}
