package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.query.common.BatchRunInErrorViewRow;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;
import com.cylande.unitedretail.framework.business.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunInErrorViewRowImpl extends ViewRowImpl implements BatchRunInErrorViewRow
{
  public static final int BRUNID = 0;
  public static final int BRUNPATH = 1;
  public static final int TRUNID = 2;
  public static final int TRUNPATH = 3;
  public static final int TAUID = 4;
  public static final int BRUNSITE = 5;
  public static final int TRUNSITE = 6;
  public static final int TAUSITE = 7;

  /**This is the default constructor (do not remove)
   */
  public BatchRunInErrorViewRowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute Brunid
   */
  public Integer getBrunid()
  {
    return (Integer)getAttributeInternal(BRUNID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Brunid
   */
  public void setBrunid(Integer value)
  {
    setAttributeInternal(BRUNID, value);
  }

  /**Gets the attribute value for the calculated attribute Brunpath
   */
  public String getBrunpath()
  {
    return (String)getAttributeInternal(BRUNPATH);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Brunpath
   */
  public void setBrunpath(String value)
  {
    setAttributeInternal(BRUNPATH, value);
  }

  /**Gets the attribute value for the calculated attribute Trunid
   */
  public Integer getTrunid()
  {
    return (Integer)getAttributeInternal(TRUNID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Trunid
   */
  public void setTrunid(Integer value)
  {
    setAttributeInternal(TRUNID, value);
  }

  /**Gets the attribute value for the calculated attribute Trunpath
   */
  public String getTrunpath()
  {
    return (String)getAttributeInternal(TRUNPATH);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Trunpath
   */
  public void setTrunpath(String value)
  {
    setAttributeInternal(TRUNPATH, value);
  }

  /**Gets the attribute value for the calculated attribute Tauid
   */
  public Integer getTauid()
  {
    return (Integer)getAttributeInternal(TAUID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Tauid
   */
  public void setTauid(Integer value)
  {
    setAttributeInternal(TAUID, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case BRUNID:
        return getBrunid();
      case BRUNPATH:
        return getBrunpath();
      case TRUNID:
        return getTrunid();
      case TRUNPATH:
        return getTrunpath();
      case TAUID:
        return getTauid();
      case BRUNSITE:
        return getBrunsite();
      case TRUNSITE:
        return getTrunsite();
      case TAUSITE:
        return getTausite();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case BRUNSITE:
        setBrunsite((String)value);
        return;
      case TRUNSITE:
        setTrunsite((String)value);
        return;
      case TAUSITE:
        setTausite((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }

  /**Gets the attribute value for the calculated attribute Brunsite
   */
  public String getBrunsite()
  {
    return (String)getAttributeInternal(BRUNSITE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Brunsite
   */
  public void setBrunsite(String value)
  {
    setAttributeInternal(BRUNSITE, value);
  }

  /**Gets the attribute value for the calculated attribute Trunsite
   */
  public String getTrunsite()
  {
    return (String)getAttributeInternal(TRUNSITE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Trunsite
   */
  public void setTrunsite(String value)
  {
    setAttributeInternal(TRUNSITE, value);
  }

  /**Gets the attribute value for the calculated attribute Tausite
   */
  public String getTausite()
  {
    return (String)getAttributeInternal(TAUSITE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Tausite
   */
  public void setTausite(String value)
  {
    setAttributeInternal(TAUSITE, value);
  }
}
