package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.entity.FileProviderTraceImpl;
import com.cylande.unitedretail.batch.business.query.common.FileProviderTraceViewRow;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;
import com.cylande.unitedretail.framework.business.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileProviderTraceViewRowImpl extends ViewRowImpl implements FileProviderTraceViewRow
{
  public static final int ID = 0;
  public static final int TASKID = 1;
  public static final int TASKCODE = 2;
  public static final int SITECODE = 3;
  public static final int DOMAIN = 4;
  public static final int PROVIDERNAME = 5;
  public static final int FILEPATH = 6;
  public static final int FILENAME = 7;
  public static final int INERROR = 8;

  /**This is the default constructor (do not remove)
   */
  public FileProviderTraceViewRowImpl()
  {
  }

  /**Gets FileProviderTrace entity object.
   */
  public FileProviderTraceImpl getFileProviderTrace()
  {
    return (FileProviderTraceImpl)getEntity(0);
  }

  /**Gets the attribute value for ID using the alias name ID
   */
  public Integer getID()
  {
    return (Integer)getAttributeInternal(ID);
  }

  /**Sets <code>value</code> as attribute value for ID using the alias name ID
   */
  public void setID(Integer value)
  {
    setAttributeInternal(ID, value);
  }

  /**Gets the attribute value for TASK_ID using the alias name TaskId
   */
  public Integer getTaskId()
  {
    return (Integer)getAttributeInternal(TASKID);
  }

  /**Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId
   */
  public void setTaskId(Integer value)
  {
    setAttributeInternal(TASKID, value);
  }

  /**Gets the attribute value for TASK_CODE using the alias name TaskCode
   */
  public String getTaskCode()
  {
    return (String)getAttributeInternal(TASKCODE);
  }

  /**Sets <code>value</code> as attribute value for TASK_CODE using the alias name TaskCode
   */
  public void setTaskCode(String value)
  {
    setAttributeInternal(TASKCODE, value);
  }

  /**Gets the attribute value for SITE_CODE using the alias name SiteCode
   */
  public String getSiteCode()
  {
    return (String)getAttributeInternal(SITECODE);
  }

  /**Sets <code>value</code> as attribute value for SITE_CODE using the alias name SiteCode
   */
  public void setSiteCode(String value)
  {
    setAttributeInternal(SITECODE, value);
  }

  /**Gets the attribute value for DOMAIN using the alias name Domain
   */
  public String getDomain()
  {
    return (String)getAttributeInternal(DOMAIN);
  }

  /**Sets <code>value</code> as attribute value for DOMAIN using the alias name Domain
   */
  public void setDomain(String value)
  {
    setAttributeInternal(DOMAIN, value);
  }

  /**Gets the attribute value for PROVIDER_NAME using the alias name ProviderName
   */
  public String getProviderName()
  {
    return (String)getAttributeInternal(PROVIDERNAME);
  }

  /**Sets <code>value</code> as attribute value for PROVIDER_NAME using the alias name ProviderName
   */
  public void setProviderName(String value)
  {
    setAttributeInternal(PROVIDERNAME, value);
  }

  /**Gets the attribute value for FILE_PATH using the alias name FilePath
   */
  public String getFilePath()
  {
    return (String)getAttributeInternal(FILEPATH);
  }

  /**Sets <code>value</code> as attribute value for FILE_PATH using the alias name FilePath
   */
  public void setFilePath(String value)
  {
    setAttributeInternal(FILEPATH, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case ID:
        return getID();
      case TASKID:
        return getTaskId();
      case TASKCODE:
        return getTaskCode();
      case SITECODE:
        return getSiteCode();
      case DOMAIN:
        return getDomain();
      case PROVIDERNAME:
        return getProviderName();
      case FILEPATH:
        return getFilePath();
      case FILENAME:
        return getFileName();
      case INERROR:
        return getInError();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case ID:
        setID((Integer)value);
        return;
      case TASKID:
        setTaskId((Integer)value);
        return;
      case TASKCODE:
        setTaskCode((String)value);
        return;
      case SITECODE:
        setSiteCode((String)value);
        return;
      case DOMAIN:
        setDomain((String)value);
        return;
      case PROVIDERNAME:
        setProviderName((String)value);
        return;
      case FILEPATH:
        setFilePath((String)value);
        return;
      case FILENAME:
        setFileName((String)value);
        return;
      case INERROR:
        setInError((Booleans)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }

  /**Gets the attribute value for FILE_NAME using the alias name FileName
   */
  public String getFileName()
  {
    return (String) getAttributeInternal(FILENAME);
  }

  /**Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName
   */
  public void setFileName(String value)
  {
    setAttributeInternal(FILENAME, value);
  }

  /**Gets the attribute value for IN_ERROR using the alias name InError
   */
  public Booleans getInError()
  {
    return (Booleans)getAttributeInternal(INERROR);
  }

  /**Sets <code>value</code> as attribute value for IN_ERROR using the alias name InError
   */
  public void setInError(Booleans value)
  {
    setAttributeInternal(INERROR, value);
  }
}
