package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.entity.ProviderCrcImpl;
import com.cylande.unitedretail.batch.business.query.common.ProviderCrcViewRow;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Timestamp;
import com.cylande.unitedretail.framework.business.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProviderCrcViewRowImpl extends ViewRowImpl implements ProviderCrcViewRow
{
  public static final int CRC = 0;
  public static final int BATCHNAME = 1;
  public static final int OVERRIDDEN = 2;
  public static final int CREATIONTIME = 3;
  public static final int CREATIONUSERCODE = 4;
  public static final int MODIFICATIONTIME = 5;
  public static final int MODIFICATIONUSERCODE = 6;

  /**This is the default constructor (do not remove)
   */
  public ProviderCrcViewRowImpl()
  {
  }

  /**Gets ProviderCrc entity object.
   */
  public ProviderCrcImpl getProviderCrc()
  {
    return (ProviderCrcImpl)getEntity(0);
  }

  /**Gets the attribute value for CRC using the alias name Crc
   */
  public String getCrc()
  {
    return (String)getAttributeInternal(CRC);
  }

  /**Sets <code>value</code> as attribute value for CRC using the alias name Crc
   */
  public void setCrc(String value)
  {
    setAttributeInternal(CRC, value);
  }

  /**Gets the attribute value for BATCH_NAME using the alias name BatchName
   */
  public String getBatchName()
  {
    return (String)getAttributeInternal(BATCHNAME);
  }

  /**Sets <code>value</code> as attribute value for BATCH_NAME using the alias name BatchName
   */
  public void setBatchName(String value)
  {
    setAttributeInternal(BATCHNAME, value);
  }

  /**Gets the attribute value for OVERRIDDEN using the alias name Overridden
   */
  public Booleans getOverridden()
  {
    return (Booleans)getAttributeInternal(OVERRIDDEN);
  }

  /**Sets <code>value</code> as attribute value for OVERRIDDEN using the alias name Overridden
   */
  public void setOverridden(Booleans value)
  {
    setAttributeInternal(OVERRIDDEN, value);
  }

  /**Gets the attribute value for CREATION_DATE using the alias name CreationTime
   */
  public Timestamp getCreationTime()
  {
    return (Timestamp)getAttributeInternal(CREATIONTIME);
  }

  /**Gets the attribute value for CREATION_USER_CODE using the alias name CreationUserCode
   */
  public String getCreationUserCode()
  {
    return (String)getAttributeInternal(CREATIONUSERCODE);
  }

  /**Gets the attribute value for CREATION_USER_CODE using the alias name ModificationTime
   */
  public Timestamp getModificationTime()
  {
    return (Timestamp)getAttributeInternal(MODIFICATIONTIME);
  }

  /**Gets the attribute value for MODIFICATION_USER_CODE using the alias name ModificationUserCode
   */
  public String getModificationUserCode()
  {
    return (String)getAttributeInternal(MODIFICATIONUSERCODE);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case CRC:
        return getCrc();
      case BATCHNAME:
        return getBatchName();
      case OVERRIDDEN:
        return getOverridden();
      case CREATIONTIME:
        return getCreationTime();
      case CREATIONUSERCODE:
        return getCreationUserCode();
      case MODIFICATIONTIME:
        return getModificationTime();
      case MODIFICATIONUSERCODE:
        return getModificationUserCode();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case CRC:
        setCrc((String)value);
        return;
      case BATCHNAME:
        setBatchName((String)value);
        return;
      case OVERRIDDEN:
        setOverridden((Booleans)value);
        return;
      case MODIFICATIONTIME:
        setModificationTime((Timestamp)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }

  /**Sets <code>value</code> as attribute value for MODIFICATION_TIME using the alias name ModificationTime
   */
  public void setModificationTime(Timestamp value)
  {
    setAttributeInternal(MODIFICATIONTIME, value);
  }
}
