package com.cylande.unitedretail.batch.business.query;

import com.cylande.unitedretail.batch.business.entity.TaskAuditImpl;
import com.cylande.unitedretail.batch.business.query.common.TaskAuditViewRow;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Timestamp;
import com.cylande.unitedretail.framework.business.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskAuditViewRowImpl extends ViewRowImpl implements TaskAuditViewRow
{
  public static final int CREATIONTIME = 0;
  public static final int CREATIONUSERCODE = 1;
  public static final int MODIFICATIONTIME = 2;
  public static final int MODIFICATIONUSERCODE = 3;
  public static final int PATH = 4;
  public static final int ID = 5;
  public static final int EVENTTIME = 6;
  public static final int ERRORCODE = 7;
  public static final int ERRORMESSAGE = 8;
  public static final int TASK = 9;
  public static final int SITECODE = 10;
  public static final int FILEID = 11;

  /**This is the default constructor (do not remove)
   */
  public TaskAuditViewRowImpl()
  {
  }

  /**Gets TaskAudit entity object.
   */
  public TaskAuditImpl getTaskAudit()
  {
    return (TaskAuditImpl)getEntity(0);
  }

  /**Gets the attribute value for CREATION_TIME using the alias name CreationTime
   */
  public Timestamp getCreationTime()
  {
    return (Timestamp)getAttributeInternal(CREATIONTIME);
  }

  /**Gets the attribute value for CREATION_USER_CODE using the alias name CreationUserCode
   */
  public String getCreationUserCode()
  {
    return (String)getAttributeInternal(CREATIONUSERCODE);
  }

  /**Gets the attribute value for MODIFICATION_TIME using the alias name ModificationTime
   */
  public Timestamp getModificationTime()
  {
    return (Timestamp)getAttributeInternal(MODIFICATIONTIME);
  }

  /**Gets the attribute value for MODIFICATION_USER_CODE using the alias name ModificationUserCode
   */
  public String getModificationUserCode()
  {
    return (String)getAttributeInternal(MODIFICATIONUSERCODE);
  }

  /**Gets the attribute value for TASK_CODE using the alias name Path
   */
  public String getPath()
  {
    return (String)getAttributeInternal(PATH);
  }

  /**Sets <code>value</code> as attribute value for TASK_CODE using the alias name Path
   */
  public void setPath(String value)
  {
    setAttributeInternal(PATH, value);
  }

  /**Gets the attribute value for ID using the alias name Id
   */
  public Integer getId()
  {
    return (Integer)getAttributeInternal(ID);
  }

  /**Sets <code>value</code> as attribute value for ID using the alias name Id
   */
  public void setId(Integer value)
  {
    setAttributeInternal(ID, value);
  }

  /**Gets the attribute value for EVENT_TIME using the alias name EventTime
   */
  public Timestamp getEventTime()
  {
    return (Timestamp)getAttributeInternal(EVENTTIME);
  }

  /**Sets <code>value</code> as attribute value for EVENT_TIME using the alias name EventTime
   */
  public void setEventTime(Timestamp value)
  {
    setAttributeInternal(EVENTTIME, value);
  }

  /**Gets the attribute value for ERROR_CODE using the alias name ErrorCode
   */
  public String getErrorCode()
  {
    return (String)getAttributeInternal(ERRORCODE);
  }

  /**Sets <code>value</code> as attribute value for ERROR_CODE using the alias name ErrorCode
   */
  public void setErrorCode(String value)
  {
    setAttributeInternal(ERRORCODE, value);
  }

  /**Gets the attribute value for ERROR_MESSAGE using the alias name ErrorMessage
   */
  public String getErrorMessage()
  {
    return (String)getAttributeInternal(ERRORMESSAGE);
  }

  /**Sets <code>value</code> as attribute value for ERROR_MESSAGE using the alias name ErrorMessage
   */
  public void setErrorMessage(String value)
  {
    if ((value != null) && (value.length() > 255))
    {
      value = value.substring(0, 252) + "...";
    }
    setAttributeInternal(ERRORMESSAGE, value);
  }

  /**Gets the attribute value for TASK using the alias name Task
   */
  public Integer getTask()
  {
    return (Integer)getAttributeInternal(TASK);
  }

  /**Sets <code>value</code> as attribute value for TASK using the alias name Task
   */
  public void setTask(Integer value)
  {
    setAttributeInternal(TASK, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case CREATIONTIME:
        return getCreationTime();
      case CREATIONUSERCODE:
        return getCreationUserCode();
      case MODIFICATIONTIME:
        return getModificationTime();
      case MODIFICATIONUSERCODE:
        return getModificationUserCode();
      case PATH:
        return getPath();
      case ID:
        return getId();
      case EVENTTIME:
        return getEventTime();
      case ERRORCODE:
        return getErrorCode();
      case ERRORMESSAGE:
        return getErrorMessage();
      case TASK:
        return getTask();
      case SITECODE:
        return getSiteCode();
      case FILEID:
        return getFileId();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
      case PATH:
        setPath((String)value);
        return;
      case ID:
        setId((Integer)value);
        return;
      case EVENTTIME:
        setEventTime((Timestamp)value);
        return;
      case ERRORCODE:
        setErrorCode((String)value);
        return;
      case ERRORMESSAGE:
        setErrorMessage((String)value);
        return;
      case TASK:
        setTask((Integer)value);
        return;
      case SITECODE:
        setSiteCode((String)value);
        return;
      case FILEID:
        setFileId((Integer)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
  }

  /**Gets the attribute value for SITE_CODE using the alias name SiteCode
   */
  public String getSiteCode()
  {
    return (String)getAttributeInternal(SITECODE);
  }

  /**Sets <code>value</code> as attribute value for SITE_CODE using the alias name SiteCode
   */
  public void setSiteCode(String value)
  {
    setAttributeInternal(SITECODE, value);
  }

  /**Gets the attribute value for FILE_ID using the alias name FileId
   */
  public Integer getFileId()
  {
    return (Integer)getAttributeInternal(FILEID);
  }

  /**Sets <code>value</code> as attribute value for FILE_ID using the alias name FileId
   */
  public void setFileId(Integer value)
  {
    setAttributeInternal(FILEID, value);
  }
}
