--
-- Création des index orientés perfs sous Oracle DB
-- Les indexs uniques sont dores et déjà gérés par dbSynchro
-- Les indexs perfs seront eux aussi à terme gérés par dbSynchro
-- Contient tous les indexs apparus depuis la dernière version figée
--

-- A l'attention de la communauté de développeurs :
-- > Pensez à préfixer tous les commentaires de '--'
-- > Veillez à ajouter vos mises à jour en entête du fichier (les plus anciennes sont en bas)
-- > Merci de précéder votre mise à jour des informations suivantes : 
--   Date : jj/mm/aaaa
--   Autheur : nom prénom
--   Version : w.x.y-z -> Courante (remarque : w.x.y-z n'est pas égal à 'Courante', il s'agit de la dernière version figée : majeure (w.x), mineure (y), niveau de patch (z))
--   Comentaire
