package com.cylande.unitedretail.batch.business.module.client;

import com.cylande.unitedretail.batch.business.module.common.BatchApplicationModule;
import com.cylande.unitedretail.message.common.CommonScenarioType;
import com.cylande.unitedretail.message.common.context.ContextType;
import com.cylande.unitedretail.message.common.processapplication.ProcessIndicatorType;
import com.cylande.unitedretail.message.common.processapplication.ProcessSiteIndicatorListType;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchApplicationModuleClient extends ApplicationModuleImpl implements BatchApplicationModule
{
  /**This is the default constructor (do not remove)
   */
  public BatchApplicationModuleClient()
  {
  }

  public ProcessSiteIndicatorListType findBatchSiteIndicator(CommonScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"findBatchSiteIndicator",new String [] {"com.cylande.unitedretail.message.common.CommonScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pScenario, pContext});
    return (ProcessSiteIndicatorListType)_ret;
  }

  public ProcessIndicatorType getBatchIndicator(CommonScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getBatchIndicator",new String [] {"com.cylande.unitedretail.message.common.CommonScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pScenario, pContext});
    return (ProcessIndicatorType)_ret;
  }
}
