package com.cylande.unitedretail.batch.business.module.client;

import com.cylande.unitedretail.batch.business.module.common.BatchRunManagerModule;
import com.cylande.unitedretail.message.batch.BatchBooleanResponseType;
import com.cylande.unitedretail.message.batch.BatchCriteriaType;
import com.cylande.unitedretail.message.batch.BatchRunCriteriaListType;
import com.cylande.unitedretail.message.batch.BatchRunCriteriaType;
import com.cylande.unitedretail.message.batch.BatchRunKeyType;
import com.cylande.unitedretail.message.batch.BatchRunListType;
import com.cylande.unitedretail.message.batch.BatchRunNameListType;
import com.cylande.unitedretail.message.batch.BatchRunScenarioType;
import com.cylande.unitedretail.message.batch.BatchRunType;
import com.cylande.unitedretail.message.batch.BatchStatusScenarioType;
import com.cylande.unitedretail.message.batch.BatchSummaryCriteriaCondensaType;
import com.cylande.unitedretail.message.batch.BatchSummaryCriteriaType;
import com.cylande.unitedretail.message.batch.TaskAuditListType;
import com.cylande.unitedretail.message.batch.TaskRunListType;
import com.cylande.unitedretail.message.common.context.ContextType;
import com.cylande.unitedretail.message.common.criteria.CriteriaStringType;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchRunManagerModuleClient extends ApplicationModuleImpl implements BatchRunManagerModule
{
  /**This is the default constructor (do not remove)
   */
  public BatchRunManagerModuleClient()
  {
  }

  public BatchRunNameListType findBatchRunSummary(BatchSummaryCriteriaType pParams, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "findBatchRunSummary", new String[] { "com.cylande.unitedretail.message.batch.BatchSummaryCriteriaType", "com.cylande.unitedretail.message.batch.BatchRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pParams, pScenario, pContext });
    return (BatchRunNameListType)_ret;
  }

  public BatchBooleanResponseType atLeastBatchInstanceIsRunning(CriteriaStringType pBatchNameCrit, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "atLeastBatchInstanceIsRunning", new String[] { "com.cylande.unitedretail.message.common.criteria.CriteriaStringType", "com.cylande.unitedretail.message.batch.BatchRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pBatchNameCrit, pScenario, pContext });
    return (BatchBooleanResponseType)_ret;
  }

  public BatchBooleanResponseType atLeastBatchInstanceIsRunning(BatchCriteriaType pBatchCrit, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "atLeastBatchInstanceIsRunning", new String[] { "com.cylande.unitedretail.message.batch.BatchCriteriaType", "com.cylande.unitedretail.message.batch.BatchRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pBatchCrit, pScenario, pContext });
    return (BatchBooleanResponseType)_ret;
  }

  public BatchBooleanResponseType atLeastBatchInstanceInError(BatchRunCriteriaType pCriteria, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"atLeastBatchInstanceInError",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pCriteria, pScenario, pContext});
    return (BatchBooleanResponseType)_ret;
  }

  public BatchRunType getLastActivationBatch(BatchCriteriaType pBatchCrit, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getLastActivationBatch",new String [] {"com.cylande.unitedretail.message.batch.BatchCriteriaType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pBatchCrit, pScenario, pContext});
    return (BatchRunType)_ret;
  }

  public BatchBooleanResponseType atLeastBatchInstanceInError(BatchCriteriaType pCriteria, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"atLeastBatchInstanceInError",new String [] {"com.cylande.unitedretail.message.batch.BatchCriteriaType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pCriteria, pScenario, pContext});
    return (BatchBooleanResponseType)_ret;
  }

  public BatchBooleanResponseType atLeastBatchInstanceIsRunning(BatchRunCriteriaType pBatchCrit, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"atLeastBatchInstanceIsRunning",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pBatchCrit, pScenario, pContext});
    return (BatchBooleanResponseType)_ret;
  }

  public BatchBooleanResponseType atLeastTaskError(BatchRunKeyType pKey, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"atLeastTaskError",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pKey, pScenario, pContext});
    return (BatchBooleanResponseType)_ret;
  }

  public boolean batchRunIsOnError(BatchRunKeyType pKey)
  {
    Object _ret = this.riInvokeExportedMethod(this,"batchRunIsOnError",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType"},new Object[] {pKey});
    return ((Boolean)_ret).booleanValue();
  }

  public BatchRunType createBatchRun(BatchRunType pBatchRun, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"createBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pBatchRun, pScenario, pContext});
    return (BatchRunType)_ret;
  }

  public BatchRunListType createBatchRunList(BatchRunListType pList, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"createBatchRunList",new String [] {"com.cylande.unitedretail.message.batch.BatchRunListType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pList, pScenario, pContext});
    return (BatchRunListType)_ret;
  }

  public void deleteBatchRun(BatchRunKeyType pKey, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"deleteBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pKey, pScenario, pContext});
    return;
  }

  public void deleteBatchRunList(BatchRunCriteriaListType pCriterias, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"deleteBatchRunList",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaListType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pCriterias, pScenario, pContext});
    return;
  }

  public void deleteBatchRunPacket(BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"deleteBatchRunPacket",new String [] {"com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pScenario, pContext});
    return;
  }

  public BatchRunListType findBatchRun(BatchRunCriteriaListType pCriterias, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"findBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaListType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pCriterias, pScenario, pContext});
    return (BatchRunListType)_ret;
  }

  public BatchRunNameListType findBatchRunSummary(BatchSummaryCriteriaCondensaType pParams, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"findBatchRunSummary",new String [] {"com.cylande.unitedretail.message.batch.BatchSummaryCriteriaCondensaType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pParams, pScenario, pContext});
    return (BatchRunNameListType)_ret;
  }

  public BatchRunType getBatchRun(BatchRunKeyType pKey, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pKey, pScenario, pContext});
    return (BatchRunType)_ret;
  }

  public BatchRunListType getBatchRunOfBatchRun(BatchRunKeyType pKey, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getBatchRunOfBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pKey, pScenario, pContext});
    return (BatchRunListType)_ret;
  }

  public BatchRunType getLastActivationBatch(BatchRunCriteriaType pBatchCrit, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getLastActivationBatch",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pBatchCrit, pScenario, pContext});
    return (BatchRunType)_ret;
  }

  public BatchRunType getLastBatchInProgress(BatchRunKeyType pKey, BatchStatusScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getLastBatchInProgress",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType","com.cylande.unitedretail.message.batch.BatchStatusScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pKey, pScenario, pContext});
    return (BatchRunType)_ret;
  }

  public TaskAuditListType getTaskAuditOfBatchRun(BatchRunKeyType pKey, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getTaskAuditOfBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pKey, pScenario, pContext});
    return (TaskAuditListType)_ret;
  }

  public TaskRunListType getTaskRunOfBatchRun(BatchRunKeyType pKey, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"getTaskRunOfBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunKeyType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pKey, pScenario, pContext});
    return (TaskRunListType)_ret;
  }

  public boolean hasNextPacketToDelete()
  {
    Object _ret = this.riInvokeExportedMethod(this,"hasNextPacketToDelete",null,null);
    return ((Boolean)_ret).booleanValue();
  }

  public void initDeleteBatchRunList(BatchRunCriteriaListType pCriterias)
  {
    Object _ret = this.riInvokeExportedMethod(this,"initDeleteBatchRunList",new String [] {"com.cylande.unitedretail.message.batch.BatchRunCriteriaListType"},new Object[] {pCriterias});
    return;
  }

  public BatchRunType postBatchRun(BatchRunType pBatchRun, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"postBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pBatchRun, pScenario, pContext});
    return (BatchRunType)_ret;
  }

  public BatchRunListType postBatchRunList(BatchRunListType pList, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"postBatchRunList",new String [] {"com.cylande.unitedretail.message.batch.BatchRunListType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pList, pScenario, pContext});
    return (BatchRunListType)_ret;
  }

  public void releaseDeleteBatchRunList()
  {
    Object _ret = this.riInvokeExportedMethod(this,"releaseDeleteBatchRunList",null,null);
    return;
  }

  public BatchRunType updateBatchRun(BatchRunType pBatchRun, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"updateBatchRun",new String [] {"com.cylande.unitedretail.message.batch.BatchRunType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pBatchRun, pScenario, pContext});
    return (BatchRunType)_ret;
  }

  public BatchRunListType updateBatchRunList(BatchRunListType pList, BatchRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this,"updateBatchRunList",new String [] {"com.cylande.unitedretail.message.batch.BatchRunListType","com.cylande.unitedretail.message.batch.BatchRunScenarioType","com.cylande.unitedretail.message.common.context.ContextType"},new Object[] {pList, pScenario, pContext});
    return (BatchRunListType)_ret;
  }
}
