package com.cylande.unitedretail.batch.business.module.client;

import com.cylande.unitedretail.batch.business.module.common.FileProviderTraceManagerModule;
import com.cylande.unitedretail.message.batch.FileProviderTraceCriteriaListType;
import com.cylande.unitedretail.message.batch.FileProviderTraceKeyType;
import com.cylande.unitedretail.message.batch.FileProviderTraceListType;
import com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType;
import com.cylande.unitedretail.message.batch.FileProviderTraceType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileProviderTraceManagerModuleClient extends ApplicationModuleImpl implements FileProviderTraceManagerModule
{
  /**This is the default constructor (do not remove)
   */
  public FileProviderTraceManagerModuleClient()
  {
  }

  public FileProviderTraceType createFileProviderTrace(FileProviderTraceType pFileProviderTrace, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "createFileProviderTrace", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pFileProviderTrace, pScenario, pContext });
    return (FileProviderTraceType)_ret;
  }

  public FileProviderTraceListType createFileProviderTraceList(FileProviderTraceListType pList, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "createFileProviderTraceList", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceListType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (FileProviderTraceListType)_ret;
  }

  public void deleteFileProviderTrace(FileProviderTraceKeyType pKey, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "deleteFileProviderTrace", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceKeyType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return;
  }

  public void deleteFileProviderTraceList(FileProviderTraceCriteriaListType pCriterias, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "deleteFileProviderTraceList", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceCriteriaListType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pCriterias, pScenario, pContext });
    return;
  }

  public FileProviderTraceListType findFileProviderTrace(FileProviderTraceCriteriaListType pCriterias, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "findFileProviderTrace", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceCriteriaListType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pCriterias, pScenario, pContext });
    return (FileProviderTraceListType)_ret;
  }

  public FileProviderTraceType getFileProviderTrace(FileProviderTraceKeyType pKey, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "getFileProviderTrace", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceKeyType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return (FileProviderTraceType)_ret;
  }

  public FileProviderTraceType postFileProviderTrace(FileProviderTraceType pFileProviderTrace, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "postFileProviderTrace", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pFileProviderTrace, pScenario, pContext });
    return (FileProviderTraceType)_ret;
  }

  public FileProviderTraceListType postFileProviderTraceList(FileProviderTraceListType pList, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "postFileProviderTraceList", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceListType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (FileProviderTraceListType)_ret;
  }

  public FileProviderTraceType updateFileProviderTrace(FileProviderTraceType pFileProviderTrace, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "updateFileProviderTrace", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pFileProviderTrace, pScenario, pContext });
    return (FileProviderTraceType)_ret;
  }

  public FileProviderTraceListType updateFileProviderTraceList(FileProviderTraceListType pList, FileProviderTraceScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "updateFileProviderTraceList", new String[] { "com.cylande.unitedretail.message.batch.FileProviderTraceListType", "com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (FileProviderTraceListType)_ret;
  }
}
