package com.cylande.unitedretail.batch.business.module.client;

import com.cylande.unitedretail.batch.business.module.common.ProviderCrcManagerModule;
import com.cylande.unitedretail.message.batch.ProviderCrcKeyType;
import com.cylande.unitedretail.message.batch.ProviderCrcScenarioType;
import com.cylande.unitedretail.message.batch.ProviderCrcType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProviderCrcManagerModuleClient extends ApplicationModuleImpl implements ProviderCrcManagerModule
{
  /**This is the default constructor (do not remove)
   */
  public ProviderCrcManagerModuleClient()
  {
  }

  public ProviderCrcType createProviderCrc(ProviderCrcType pProviderCrc, ProviderCrcScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "createProviderCrc", new String[] { "com.cylande.unitedretail.message.batch.ProviderCrcType", "com.cylande.unitedretail.message.batch.ProviderCrcScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pProviderCrc, pScenario, pContext });
    return (ProviderCrcType)_ret;
  }

  public void deleteProviderCrc(ProviderCrcKeyType pKey, ProviderCrcScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "deleteProviderCrc", new String[] { "com.cylande.unitedretail.message.batch.ProviderCrcKeyType", "com.cylande.unitedretail.message.batch.ProviderCrcScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return;
  }

  public ProviderCrcType getProviderCrc(ProviderCrcKeyType pKey, ProviderCrcScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "getProviderCrc", new String[] { "com.cylande.unitedretail.message.batch.ProviderCrcKeyType", "com.cylande.unitedretail.message.batch.ProviderCrcScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return (ProviderCrcType)_ret;
  }

  public ProviderCrcType postProviderCrc(ProviderCrcType pProviderCrc, ProviderCrcScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "postProviderCrc", new String[] { "com.cylande.unitedretail.message.batch.ProviderCrcType", "com.cylande.unitedretail.message.batch.ProviderCrcScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pProviderCrc, pScenario, pContext });
    return (ProviderCrcType)_ret;
  }

  public ProviderCrcType removeProviderCrc(ProviderCrcKeyType pKey, ProviderCrcScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "removeProviderCrc", new String[] { "com.cylande.unitedretail.message.batch.ProviderCrcKeyType", "com.cylande.unitedretail.message.batch.ProviderCrcScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return (ProviderCrcType)_ret;
  }

  public ProviderCrcType updateProviderCrc(ProviderCrcType pProviderCrc, ProviderCrcScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "updateProviderCrc", new String[] { "com.cylande.unitedretail.message.batch.ProviderCrcType", "com.cylande.unitedretail.message.batch.ProviderCrcScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pProviderCrc, pScenario, pContext });
    return (ProviderCrcType)_ret;
  }
}
