package com.cylande.unitedretail.batch.business.module.client;

import com.cylande.unitedretail.batch.business.module.common.FileProviderTraceManagerModule;
import com.cylande.unitedretail.batch.business.module.common.TaskRunManagerModule;
import com.cylande.unitedretail.message.batch.TaskAuditListType;
import com.cylande.unitedretail.message.batch.TaskBooleanResponseType;
import com.cylande.unitedretail.message.batch.TaskRunCriteriaListType;
import com.cylande.unitedretail.message.batch.TaskRunKeyType;
import com.cylande.unitedretail.message.batch.TaskRunListType;
import com.cylande.unitedretail.message.batch.TaskRunScenarioType;
import com.cylande.unitedretail.message.batch.TaskRunType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskRunManagerModuleClient extends ApplicationModuleImpl implements TaskRunManagerModule
{
  /**This is the default constructor (do not remove)
   */
  public TaskRunManagerModuleClient()
  {
  }

  public TaskBooleanResponseType atLeastTaskError(TaskRunKeyType pTaskRunKey, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "atLeastTaskError", new String[] { "com.cylande.unitedretail.message.batch.TaskRunKeyType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pTaskRunKey, pScenario, pContext });
    return (TaskBooleanResponseType)_ret;
  }

  public TaskRunType createTaskRun(TaskRunType pTaskRun, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "createTaskRun", new String[] { "com.cylande.unitedretail.message.batch.TaskRunType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pTaskRun, pScenario, pContext });
    return (TaskRunType)_ret;
  }

  public TaskRunListType createTaskRunList(TaskRunListType pList, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "createTaskRunList", new String[] { "com.cylande.unitedretail.message.batch.TaskRunListType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (TaskRunListType)_ret;
  }

  public void deleteTaskRun(TaskRunKeyType pKey, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "deleteTaskRun", new String[] { "com.cylande.unitedretail.message.batch.TaskRunKeyType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return;
  }

  public void deleteTaskRunList(TaskRunCriteriaListType pCriterias, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "deleteTaskRunList", new String[] { "com.cylande.unitedretail.message.batch.TaskRunCriteriaListType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pCriterias, pScenario, pContext });
    return;
  }

  public TaskRunListType findTaskRun(TaskRunCriteriaListType pCriterias, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "findTaskRun", new String[] { "com.cylande.unitedretail.message.batch.TaskRunCriteriaListType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pCriterias, pScenario, pContext });
    return (TaskRunListType)_ret;
  }

  public FileProviderTraceManagerModule getFileProviderTraceManagerModule()
  {
    Object _ret = this.riInvokeExportedMethod(this, "getFileProviderTraceManagerModule", null, null);
    return (FileProviderTraceManagerModule)_ret;
  }

  public TaskAuditListType getTaskAuditOfTaskRun(TaskRunKeyType pKey, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "getTaskAuditOfTaskRun", new String[] { "com.cylande.unitedretail.message.batch.TaskRunKeyType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return (TaskAuditListType)_ret;
  }

  public TaskRunType getTaskRun(TaskRunKeyType pKey, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "getTaskRun", new String[] { "com.cylande.unitedretail.message.batch.TaskRunKeyType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return (TaskRunType)_ret;
  }

  public TaskRunType postTaskRun(TaskRunType pTaskRun, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "postTaskRun", new String[] { "com.cylande.unitedretail.message.batch.TaskRunType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pTaskRun, pScenario, pContext });
    return (TaskRunType)_ret;
  }

  public TaskRunListType postTaskRunList(TaskRunListType pList, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "postTaskRunList", new String[] { "com.cylande.unitedretail.message.batch.TaskRunListType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (TaskRunListType)_ret;
  }

  public TaskRunType updateTaskRun(TaskRunType pTaskRun, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "updateTaskRun", new String[] { "com.cylande.unitedretail.message.batch.TaskRunType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pTaskRun, pScenario, pContext });
    return (TaskRunType)_ret;
  }

  public TaskRunListType updateTaskRunList(TaskRunListType pList, TaskRunScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "updateTaskRunList", new String[] { "com.cylande.unitedretail.message.batch.TaskRunListType", "com.cylande.unitedretail.message.batch.TaskRunScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (TaskRunListType)_ret;
  }
}
