package com.cylande.unitedretail.batch.business.module.client;

import com.cylande.unitedretail.batch.business.module.common.TaskAuditManagerModule;
import com.cylande.unitedretail.message.batch.TaskAuditCriteriaListType;
import com.cylande.unitedretail.message.batch.TaskAuditKeyType;
import com.cylande.unitedretail.message.batch.TaskAuditListType;
import com.cylande.unitedretail.message.batch.TaskAuditScenarioType;
import com.cylande.unitedretail.message.batch.TaskAuditType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskAuditManagerModuleClient extends ApplicationModuleImpl implements TaskAuditManagerModule
{
  /**This is the default constructor (do not remove)
   */
  public TaskAuditManagerModuleClient()
  {
  }

  public TaskAuditType createTaskAudit(TaskAuditType pTaskAudit, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "createTaskAudit", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pTaskAudit, pScenario, pContext });
    return (TaskAuditType)_ret;
  }

  public TaskAuditListType createTaskAuditList(TaskAuditListType pList, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "createTaskAuditList", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditListType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (TaskAuditListType)_ret;
  }

  public void deleteTaskAudit(TaskAuditKeyType pKey, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "deleteTaskAudit", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditKeyType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return;
  }

  public void deleteTaskAuditList(TaskAuditCriteriaListType pCriterias, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "deleteTaskAuditList", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditCriteriaListType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pCriterias, pScenario, pContext });
    return;
  }

  public TaskAuditListType findTaskAudit(TaskAuditCriteriaListType pCriterias, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "findTaskAudit", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditCriteriaListType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pCriterias, pScenario, pContext });
    return (TaskAuditListType)_ret;
  }

  public TaskAuditType getTaskAudit(TaskAuditKeyType pKey, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "getTaskAudit", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditKeyType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pKey, pScenario, pContext });
    return (TaskAuditType)_ret;
  }

  public TaskAuditType postTaskAudit(TaskAuditType pTaskAudit, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "postTaskAudit", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pTaskAudit, pScenario, pContext });
    return (TaskAuditType)_ret;
  }

  public TaskAuditListType postTaskAuditList(TaskAuditListType pList, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "postTaskAuditList", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditListType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (TaskAuditListType)_ret;
  }

  public TaskAuditType updateTaskAudit(TaskAuditType pTaskAudit, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "updateTaskAudit", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pTaskAudit, pScenario, pContext });
    return (TaskAuditType)_ret;
  }

  public TaskAuditListType updateTaskAuditList(TaskAuditListType pList, TaskAuditScenarioType pScenario, ContextType pContext)
  {
    Object _ret = this.riInvokeExportedMethod(this, "updateTaskAuditList", new String[] { "com.cylande.unitedretail.message.batch.TaskAuditListType", "com.cylande.unitedretail.message.batch.TaskAuditScenarioType", "com.cylande.unitedretail.message.common.context.ContextType" }, new Object[] { pList, pScenario, pContext });
    return (TaskAuditListType)_ret;
  }
}
