package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchRunViewRow extends Row
{
  RowIterator getBatchRunChildrenView();

  RowIterator getTaskRunChildrenView();

  String getBatchMode();

  String getBatchType();

  Timestamp getCreationTime();

  String getCreationUserCode();

  String getDomain();

  Timestamp getEndTime();

  Integer getId();

  Timestamp getModificationTime();

  String getModificationUserCode();

  Integer getParentId();

  String getPath();

  String getSiteCode();

  Timestamp getStartTime();

  Booleans getStatus();

  void setBatchMode(String value);

  void setBatchType(String value);

  void setDomain(String value);

  void setEndTime(Timestamp value);

  void setId(Integer value);

  void setParentId(Integer value);

  void setPath(String value);

  void setSiteCode(String value);

  void setStartTime(Timestamp value);

  void setStatus(Booleans value);

    Booleans getInError();

    void setInError(Booleans value);
}
