package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchRunInErrorViewRow extends Row
{
  Integer getBrunid();

  String getBrunpath();

  Integer getTauid();

  Integer getTrunid();

  String getTrunpath();

  void setBrunid(Integer value);

  void setBrunpath(String value);

  void setTauid(Integer value);

  void setTrunid(Integer value);

  void setTrunpath(String value);
}
