package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.message.batch.BatchCriteriaType;
import com.cylande.unitedretail.message.batch.BatchRunCriteriaListType;
import com.cylande.unitedretail.message.batch.BatchRunCriteriaType;
import com.cylande.unitedretail.message.batch.BatchRunKeyType;
import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchRunView extends ViewObject {

  void findByCriterias(BatchRunCriteriaListType pCriterias);

  BatchRunViewRow getRow(BatchRunKeyType pKey);

  BatchRunViewRow getRowByBatchId(String pPath, Integer pId, SiteKeyType pSite);

  void findLastActivationOfBatch(BatchCriteriaType pCriteria);


    boolean atLeastInstanceIsRunning(BatchRunCriteriaType pCriteria);

    boolean atLeastInstanceIsRunning(BatchCriteriaType pCriteria);

    void findLastActivationOfBatch(BatchRunCriteriaType pCriteria);
}
