package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchRunNameListView extends ViewObject
{

  void resetWhereClause();

  void findBatchRunRoot(SiteKeyType pSite);

  void findBatchRunRoot(String substring, SiteKeyType pSite);
}
