package com.cylande.unitedretail.batch.business.query.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchInProgressView extends ViewObject
{
  void findLastBatchByPath(String pPath);
}
