package com.cylande.unitedretail.batch.business.query.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchRunNameListViewRow extends Row
{
  String getBrunpath();

  void setBrunpath(String value);
}
