package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchRunInErrorView extends ViewObject
{
  void findBatchInError();

  void findTaskAudit(int pBatchId, SiteKeyType pSite);
}
