package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.message.batch.FileProviderTraceCriteriaListType;
import com.cylande.unitedretail.message.batch.FileProviderTraceKeyType;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface FileProviderTraceView extends ViewObject
{
  void findByCriterias(FileProviderTraceCriteriaListType pCriterias);

  FileProviderTraceViewRow getRow(FileProviderTraceKeyType pKey);
}
