package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface FileProviderTraceViewRow extends Row
{
  String getDomain();

  String getFileName();

  String getFilePath();

  Integer getID();

  Booleans getInError();

  String getProviderName();

  String getSiteCode();

  String getTaskCode();

  Integer getTaskId();

  void setDomain(String value);

  void setFileName(String value);

  void setFilePath(String value);

  void setID(Integer value);

  void setInError(Booleans value);

  void setProviderName(String value);

  void setSiteCode(String value);

  void setTaskCode(String value);

  void setTaskId(Integer value);
}
