package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Timestamp;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ProviderCrcViewRow extends Row
{
  String getBatchName();

  String getCrc();

  Timestamp getCreationTime();

  String getCreationUserCode();

  Timestamp getModificationTime();

  String getModificationUserCode();

  Booleans getOverridden();

  void setBatchName(String value);

  void setCrc(String value);

  void setModificationTime(Timestamp value);

  void setOverridden(Booleans value);
}
