package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.message.batch.BatchRunCriteriaType;
import com.cylande.unitedretail.message.batch.TaskAuditCriteriaListType;

import oracle.jbo.AttributeList;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface TaskAuditView extends ViewObject
{

  Row createAndInitRow(AttributeList pAttributesList);

  boolean atLeastFindResult(TaskAuditCriteriaListType pCriterias);

  void findByCriterias(TaskAuditCriteriaListType pCriterias);

  void findTaskAuditOfBatch(BatchRunCriteriaType pBatchRunCriteria);
}
