package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.message.batch.TaskRunCriteriaListType;
import com.cylande.unitedretail.message.batch.TaskRunKeyType;
import com.cylande.unitedretail.message.network.businessunit.SiteKeyType;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface TaskRunView extends ViewObject
{
  void findByCriterias(TaskRunCriteriaListType pCriterias);

  TaskRunViewRow getRow(TaskRunKeyType pKey);

  TaskRunViewRow getRowByTaskId(String pPath, Integer pId, SiteKeyType pSite);
}
