package com.cylande.unitedretail.batch.business.query.common;

import com.cylande.unitedretail.framework.business.jbo.domain.common.Booleans;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Integer;
import com.cylande.unitedretail.framework.business.jbo.domain.common.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface TaskRunViewRow extends Row
{
  RowIterator getFileProviderTraceView();

  RowIterator getTaskAuditView();

  Timestamp getCreationTime();

  String getCreationUserCode();

  String getDomain();

  Timestamp getEndTime();

  Integer getId();

  String getInputDomain();

  String getInputName();

  Timestamp getModificationTime();

  String getModificationUserCode();

  Integer getParentId();

  String getPath();

  String getProcessDomain();

  String getProcessName();

  String getRejectDomain();

  String getRejectName();

  String getResponseDomain();

  String getResponseName();

  String getSiteCode();

  Timestamp getStartTime();

  Booleans getStatus();

  String getStep();

  String getTaskType();

  Integer getWorkLoad();

  Integer getWorkProgress();

  void setDomain(String value);

  void setEndTime(Timestamp value);

  void setId(Integer value);

  void setInputDomain(String value);

  void setInputName(String value);

  void setParentId(Integer value);

  void setPath(String value);

  void setProcessDomain(String value);

  void setProcessName(String value);

  void setRejectDomain(String value);

  void setRejectName(String value);

  void setResponseDomain(String value);

  void setResponseName(String value);

  void setSiteCode(String value);

  void setStartTime(Timestamp value);

  void setStatus(Booleans value);

  void setStep(String value);

  void setTaskType(String value);

  void setWorkLoad(Integer value);

  void setWorkProgress(Integer value);

  Booleans getInError();

  void setInError(Booleans value);
}
