package com.cylande.unitedretail.batch.business.module.common;

import com.cylande.unitedretail.message.common.CommonScenarioType;
import com.cylande.unitedretail.message.common.context.ContextType;
import com.cylande.unitedretail.message.common.processapplication.ProcessIndicatorType;
import com.cylande.unitedretail.message.common.processapplication.ProcessSiteIndicatorListType;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface BatchApplicationModule extends ApplicationModule
{
  ProcessSiteIndicatorListType findBatchSiteIndicator(CommonScenarioType pScenario, ContextType pContext);

  ProcessIndicatorType getBatchIndicator(CommonScenarioType pScenario, ContextType pContext);
}
