package com.cylande.unitedretail.batch.business.module.common;

import com.cylande.unitedretail.message.batch.FileProviderTraceCriteriaListType;
import com.cylande.unitedretail.message.batch.FileProviderTraceKeyType;
import com.cylande.unitedretail.message.batch.FileProviderTraceListType;
import com.cylande.unitedretail.message.batch.FileProviderTraceScenarioType;
import com.cylande.unitedretail.message.batch.FileProviderTraceType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface FileProviderTraceManagerModule extends ApplicationModule
{
  FileProviderTraceType createFileProviderTrace(FileProviderTraceType pFileProviderTrace, FileProviderTraceScenarioType pScenario, ContextType pContext);

  FileProviderTraceListType createFileProviderTraceList(FileProviderTraceListType pList, FileProviderTraceScenarioType pScenario, ContextType pContext);

  void deleteFileProviderTrace(FileProviderTraceKeyType pKey, FileProviderTraceScenarioType pScenario, ContextType pContext);

  void deleteFileProviderTraceList(FileProviderTraceCriteriaListType pCriterias, FileProviderTraceScenarioType pScenario, ContextType pContext);

  FileProviderTraceListType findFileProviderTrace(FileProviderTraceCriteriaListType pCriterias, FileProviderTraceScenarioType pScenario, ContextType pContext);

  FileProviderTraceType getFileProviderTrace(FileProviderTraceKeyType pKey, FileProviderTraceScenarioType pScenario, ContextType pContext);

  FileProviderTraceType postFileProviderTrace(FileProviderTraceType pFileProviderTrace, FileProviderTraceScenarioType pScenario, ContextType pContext);

  FileProviderTraceListType postFileProviderTraceList(FileProviderTraceListType pList, FileProviderTraceScenarioType pScenario, ContextType pContext);

  FileProviderTraceType updateFileProviderTrace(FileProviderTraceType pFileProviderTrace, FileProviderTraceScenarioType pScenario, ContextType pContext);

  FileProviderTraceListType updateFileProviderTraceList(FileProviderTraceListType pList, FileProviderTraceScenarioType pScenario, ContextType pContext);
}
