package com.cylande.unitedretail.batch.business.module.common;

import com.cylande.unitedretail.message.batch.ProviderCrcKeyType;
import com.cylande.unitedretail.message.batch.ProviderCrcScenarioType;
import com.cylande.unitedretail.message.batch.ProviderCrcType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ProviderCrcManagerModule extends ApplicationModule
{
  ProviderCrcType createProviderCrc(ProviderCrcType pProviderCrc, ProviderCrcScenarioType pScenario, ContextType pContext);

  void deleteProviderCrc(ProviderCrcKeyType pKey, ProviderCrcScenarioType pScenario, ContextType pContext);

  ProviderCrcType getProviderCrc(ProviderCrcKeyType pKey, ProviderCrcScenarioType pScenario, ContextType pContext);

  ProviderCrcType postProviderCrc(ProviderCrcType pProviderCrc, ProviderCrcScenarioType pScenario, ContextType pContext);

  ProviderCrcType removeProviderCrc(ProviderCrcKeyType pKey, ProviderCrcScenarioType pScenario, ContextType pContext);

  ProviderCrcType updateProviderCrc(ProviderCrcType pProviderCrc, ProviderCrcScenarioType pScenario, ContextType pContext);
}
