package com.cylande.unitedretail.batch.business.module.common;

import com.cylande.unitedretail.message.common.context.ContextType;
import com.cylande.unitedretail.message.common.queryselect.AnalyzeCostQueryResultType;
import com.cylande.unitedretail.message.common.queryselect.AnalyzeCostQueryScenarioType;
import com.cylande.unitedretail.message.common.queryselect.AnalyzeCostQueryType;
import com.cylande.unitedretail.message.common.queryselect.QueryResultType;
import com.cylande.unitedretail.message.common.queryselect.QuerySelectScenarioType;
import com.cylande.unitedretail.message.common.queryselect.QuerySelectType;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface QueryDBSelectManagerModule extends ApplicationModule
{
  QueryResultType querySelect(QuerySelectType pQuerySelect, QuerySelectScenarioType pScenario, ContextType pContext);

  AnalyzeCostQueryResultType analyzeCostQuery(AnalyzeCostQueryType pAnalyseCostQuery, AnalyzeCostQueryScenarioType pScenario, ContextType pContext);
}
