package com.cylande.unitedretail.batch.business.module.common;

import com.cylande.unitedretail.message.batch.TaskAuditCriteriaListType;
import com.cylande.unitedretail.message.batch.TaskAuditKeyType;
import com.cylande.unitedretail.message.batch.TaskAuditListType;
import com.cylande.unitedretail.message.batch.TaskAuditScenarioType;
import com.cylande.unitedretail.message.batch.TaskAuditType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface TaskAuditManagerModule extends ApplicationModule
{
  TaskAuditType createTaskAudit(TaskAuditType pTaskAudit, TaskAuditScenarioType pScenario, ContextType pContext);

  TaskAuditListType createTaskAuditList(TaskAuditListType pList, TaskAuditScenarioType pScenario, ContextType pContext);

  void deleteTaskAudit(TaskAuditKeyType pKey, TaskAuditScenarioType pScenario, ContextType pContext);

  void deleteTaskAuditList(TaskAuditCriteriaListType pCriterias, TaskAuditScenarioType pScenario, ContextType pContext);

  TaskAuditListType findTaskAudit(TaskAuditCriteriaListType pCriterias, TaskAuditScenarioType pScenario, ContextType pContext);

  TaskAuditType getTaskAudit(TaskAuditKeyType pKey, TaskAuditScenarioType pScenario, ContextType pContext);

  TaskAuditType postTaskAudit(TaskAuditType pTaskAudit, TaskAuditScenarioType pScenario, ContextType pContext);

  TaskAuditListType postTaskAuditList(TaskAuditListType pList, TaskAuditScenarioType pScenario, ContextType pContext);

  TaskAuditType updateTaskAudit(TaskAuditType pTaskAudit, TaskAuditScenarioType pScenario, ContextType pContext);

  TaskAuditListType updateTaskAuditList(TaskAuditListType pList, TaskAuditScenarioType pScenario, ContextType pContext);
}
