package com.cylande.unitedretail.batch.business.module.common;

import com.cylande.unitedretail.message.batch.TaskAuditListType;
import com.cylande.unitedretail.message.batch.TaskBooleanResponseType;
import com.cylande.unitedretail.message.batch.TaskRunCriteriaListType;
import com.cylande.unitedretail.message.batch.TaskRunKeyType;
import com.cylande.unitedretail.message.batch.TaskRunListType;
import com.cylande.unitedretail.message.batch.TaskRunScenarioType;
import com.cylande.unitedretail.message.batch.TaskRunType;
import com.cylande.unitedretail.message.common.context.ContextType;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface TaskRunManagerModule extends ApplicationModule
{
  TaskRunType createTaskRun(TaskRunType pTaskRun, TaskRunScenarioType pScenario, ContextType pContext);

  TaskRunListType createTaskRunList(TaskRunListType pList, TaskRunScenarioType pScenario, ContextType pContext);

  void deleteTaskRun(TaskRunKeyType pKey, TaskRunScenarioType pScenario, ContextType pContext);

  void deleteTaskRunList(TaskRunCriteriaListType pCriterias, TaskRunScenarioType pScenario, ContextType pContext);

  TaskRunListType findTaskRun(TaskRunCriteriaListType pCriterias, TaskRunScenarioType pScenario, ContextType pContext);

  TaskRunType getTaskRun(TaskRunKeyType pKey, TaskRunScenarioType pScenario, ContextType pContext);

  TaskRunType postTaskRun(TaskRunType pTaskRun, TaskRunScenarioType pScenario, ContextType pContext);

  TaskRunListType postTaskRunList(TaskRunListType pList, TaskRunScenarioType pScenario, ContextType pContext);

  TaskRunType updateTaskRun(TaskRunType pTaskRun, TaskRunScenarioType pScenario, ContextType pContext);

  TaskRunListType updateTaskRunList(TaskRunListType pList, TaskRunScenarioType pScenario, ContextType pContext);

  TaskBooleanResponseType atLeastTaskError(TaskRunKeyType pTaskRunKey, TaskRunScenarioType pScenario, ContextType pContext);

  TaskAuditListType getTaskAuditOfTaskRun(TaskRunKeyType pTaskRunKey, TaskRunScenarioType pScenario, ContextType pContext);

  FileProviderTraceManagerModule getFileProviderTraceManagerModule();
}
